"""Add trail_name, remove speed and lat/lon columns

Revision ID: 0fe36963231d
Revises: a926157626d7
Create Date: 2025-05-15 15:37:56.208650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe36963231d'
down_revision = 'a926157626d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trail_name', sa.String(), nullable=True))
        batch_op.drop_column('max_speed_mps')
        batch_op.drop_column('start_lat')
        batch_op.drop_column('average_speed_mps')
        batch_op.drop_column('end_lat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_lat', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('average_speed_mps', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('start_lat', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('max_speed_mps', sa.FLOAT(), nullable=True))
        batch_op.drop_column('trail_name')

    # ### end Alembic commands ###
