"""Create shared activity table for sharing function

Revision ID: 4a06f1f438eb
Revises: 53cb594bf7d1
Create Date: 2025-05-12 17:21:10.411975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a06f1f438eb'
down_revision = '53cb594bf7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ActivityRegistry ')
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.drop_column('calories_burned')

    op.create_table('ActivityRegistry ',
    sa.Column('upload_user_id', sa.INTEGER(), nullable=False),
    sa.Column('upload_time', sa.DATETIME(), nullable=False),
    sa.Column('activity_date', sa.DATE(), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), nullable=False),
    sa.Column('activity_length', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['upload_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_user_id', 'upload_time')
    )
    # ### end Alembic commands ###
