"""Add name to the Foreign Key in Activity Registry table

Revision ID: 53cb594bf7d1
Revises: 2eec5d2acb66
Create Date: 2025-05-08 02:29:27.654311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cb594bf7d1'
down_revision = '2eec5d2acb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ActivityRegistry ',
    sa.Column('upload_user_id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('activity_length', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['upload_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_user_id', 'upload_time')
    )
    op.drop_table('user')
    op.drop_table('activity_registry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_registry',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('upload_time', sa.DATETIME(), nullable=False),
    sa.Column('activity_date', sa.DATE(), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), nullable=False),
    sa.Column('activity_length', sa.TIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'upload_time')
    )
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('ActivityRegistry ')
    op.drop_table('Users')
    # ### end Alembic commands ###
