"""Change activity length to integer to mirror minutes

Revision ID: 79ad82ca7794
Revises: 8c2f2c302073
Create Date: 2025-05-14 22:45:30.997262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ad82ca7794'
down_revision = '8c2f2c302073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.alter_column('activity_length',
               existing_type=sa.TIME(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.alter_column('activity_length',
               existing_type=sa.Integer(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
