"""Remove user_id as it is redundant, refactor PK into email

Revision ID: 8c2f2c302073
Revises: 4a06f1f438eb
Create Date: 2025-05-12 18:25:39.339654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2f2c302073'
down_revision = '4a06f1f438eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_user_email', sa.String(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['upload_user_email'], ['email'])
        batch_op.drop_column('upload_user_id')

    with op.batch_alter_table('SharedActivity', schema=None) as batch_op:
        batch_op.alter_column('sharing_user',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('user_shared_with',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['user_shared_with'], ['email'])
        batch_op.create_foreign_key(None, 'ActivityRegistry', ['sharing_user'], ['upload_user_email'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('SharedActivity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ActivityRegistry', ['sharing_user'], ['upload_user_id'])
        batch_op.create_foreign_key(None, 'Users', ['user_shared_with'], ['user_id'])
        batch_op.alter_column('user_shared_with',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('sharing_user',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['upload_user_id'], ['user_id'])
        batch_op.drop_column('upload_user_email')

    # ### end Alembic commands ###
