"""Initial schema with correct SharedActivity PK

Revision ID: a926157626d7
Revises: 
Create Date: 2025-05-14 20:14:32.833809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a926157626d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ActivityRegistry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_user_id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('activity_length', sa.Time(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('average_speed_mps', sa.Float(), nullable=True),
    sa.Column('max_speed_mps', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.String(), nullable=True),
    sa.Column('end_lat', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['upload_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SharedActivity',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_shared_with', sa.String(), nullable=False),
    sa.Column('sharing_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['ActivityRegistry.id'], ),
    sa.ForeignKeyConstraint(['sharing_user_id'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['user_shared_with'], ['Users.email'], ),
    sa.PrimaryKeyConstraint('activity_id', 'user_shared_with', name='pk_sharedactivity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SharedActivity')
    op.drop_table('ActivityRegistry')
    op.drop_table('Users')
    # ### end Alembic commands ###
