"""Add extended activity fields

Revision ID: babc1e4e6d4c
Revises: 8c2f2c302073
Create Date: 2025-05-13 17:33:56.360157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babc1e4e6d4c'
down_revision = '8c2f2c302073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_speed_mps', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_speed_mps', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_lat', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_lat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.drop_column('end_lat')
        batch_op.drop_column('start_lat')
        batch_op.drop_column('max_speed_mps')
        batch_op.drop_column('average_speed_mps')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('distance_m')

    # ### end Alembic commands ###
