"""Change ActivityRegistry to use Sr_no as primary key

Revision ID: cdcb8eeb6d6d
Revises: babc1e4e6d4c
Create Date: 2025-05-13 17:45:18.692372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcb8eeb6d6d'
down_revision = 'babc1e4e6d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sr_no', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.drop_column('Sr_no')

    # ### end Alembic commands ###
