"""Sharing Feature

Revision ID: d7d693890967
Revises: 79ad82ca7794
Create Date: 2025-05-15 22:59:20.898810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d693890967'
down_revision = '79ad82ca7794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('distance_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_name', sa.String(), nullable=True))

    with op.batch_alter_table('SharedActivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sharing_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ActivityRegistry', ['activity_id'], ['id'])
        batch_op.create_foreign_key(None, 'Users', ['sharing_user_id'], ['user_id'])
        batch_op.drop_column('sharing_user')
        batch_op.drop_column('activity_upload_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SharedActivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_upload_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('sharing_user', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ActivityRegistry', ['activity_upload_time'], ['upload_time'])
        batch_op.create_foreign_key(None, 'ActivityRegistry', ['sharing_user'], ['upload_user_id'])
        batch_op.drop_column('sharing_user_id')
        batch_op.drop_column('activity_id')

    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.drop_column('trail_name')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('distance_m')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
