"""Modified ActivityRegistry table

Revision ID: e4875f8f34df
Revises: 53cb594bf7d1
Create Date: 2025-05-08 20:50:38.553840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4875f8f34df'
down_revision = '53cb594bf7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivityRegistry',
    sa.Column('upload_user_id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('activity_length', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['upload_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_user_id', 'upload_time')
    )
    op.drop_table('ActivityRegistry ')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivityRegistry ',
    sa.Column('upload_user_id', sa.INTEGER(), nullable=False),
    sa.Column('upload_time', sa.DATETIME(), nullable=False),
    sa.Column('activity_date', sa.DATE(), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), nullable=False),
    sa.Column('activity_length', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['upload_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_user_id', 'upload_time')
    )
    op.drop_table('ActivityRegistry')
    # ### end Alembic commands ###
