"""Move time back to a time format

Revision ID: edb31a310f80
Revises: d7d693890967
Create Date: 2025-05-16 02:32:15.293456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb31a310f80'
down_revision = 'd7d693890967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.alter_column('activity_length',
               existing_type=sa.INTEGER(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityRegistry', schema=None) as batch_op:
        batch_op.alter_column('activity_length',
               existing_type=sa.Time(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
